#

#  ./.gitignore

#  Copyright (C) 2022, Anokidev. This file is 
#  part of Anokidev's website. Anokidev's website 
#  is open-source and is licensed in MIT License.

#  This file is used as the Netlify configuration file.

#

[functions]

# Include every public files.
included_files = ["public/**"]